// _limit_set_glow.frag
// Kleinian group limit set: fractal dust as luminous boundary
// Schottky group with two generators — pairing circles on the boundary
//
// A Kleinian group is a discrete group of Möbius transformations of the Riemann sphere.
// Its limit set is the smallest closed invariant subset of the sphere boundary.
// For a Schottky group generated by two Möbius transformations, the limit set
// is a Cantor set (fractal dust) on the circle — perfect circles of shrinking radii.
//
// The Schottky construction:
//   Choose two pairs of circles C1,C1' and C2,C2' on the unit circle boundary.
//   Generator g1 maps the exterior of C1 to the interior of C1'.
//   Generator g2 maps the exterior of C2 to the interior of C2'.
//   The limit set is the intersection of all iterated images of the circles.
//   It appears as glowing fractal dust on the boundary.
//
// This shader computes the limit set by iteration:
//   For each pixel, apply the group generators as Möbius transformations
//   until escape or convergence, counting iterations for coloring.
//
// The {7,3} tiling is shown behind the limit set for context.

precision highp float;

uniform float u_time;
uniform vec2  u_resolution;

const float PI     = 3.14159265358979323846;
const float TWO_PI = 6.28318530717958647692;
const int MAX_ITER = 80;
const int LIMIT_ITER = 40;

// ── Möbius transformation: z → (az+b)/(cz+d), as complex multiplication ──
vec2 cmul(vec2 a, vec2 b) { return vec2(a.x*b.x - a.y*b.y, a.x*b.y + a.y*b.x); }
vec2 cdiv(vec2 a, vec2 b) {
    float d = dot(b,b);
    return d < 1e-20 ? vec2(1e10) : vec2(dot(a,b), a.y*b.x-a.x*b.y)/d;
}
vec2 mobius(vec2 z, vec2 a, vec2 b, vec2 c, vec2 d) {
    return cdiv(cmul(a,z)+b, cmul(c,z)+d);
}

// ── {7,3} background tiling ────────────────────────────────────────────────
struct FundTri { float rP, rQ, acx, acy, aR2; };
FundTri makeFundTri73() {
    float sp = sin(PI/7.0), sq = sin(PI/3.0);
    float D  = max(1.0 - sp*sp - sq*sq, 1e-10);
    float sa = sqrt(D)/sp, sb = sqrt(D)/sq;
    float rP = sa/(1.0+sqrt(1.0+sa*sa));
    float rQ = sb/(1.0+sqrt(1.0+sb*sb));
    float acx = (1.0+rP*rP)/(2.0*rP), acy = (1.0+rQ*rQ)/(2.0*rQ);
    return FundTri(rP, rQ, acx, acy, acx*acx+acy*acy-1.0);
}

vec2 fold73(vec2 z, out int tp) {
    FundTri tri = makeFundTri73();
    tp = 0;
    for (int i = 0; i < MAX_ITER; i++) {
        bool ch = false;
        if (z.y < 0.0) { z.y=-z.y; ch=true; }
        if (z.x < 0.0) { z.x=-z.x; ch=true; }
        vec2 dv = z - vec2(tri.acx,tri.acy);
        float d2 = dot(dv,dv);
        if (d2 < tri.aR2-1e-9) {
            z=vec2(tri.acx,tri.acy)+tri.aR2/d2*dv;
            tp^=1; ch=true;
        }
        if(!ch) break;
    }
    return z;
}

// ── Schottky group limit set iteration ─────────────────────────────────────
// Two generators of a Schottky group:
//   g(z) = (az + b) / (cz + d)  where ad - bc = 1
// We use a classical loxodromic pair with adjustable parameters.
float limitSetValue(vec2 z, float t) {
    // Animate the Schottky parameters slowly
    float phase = t * 0.3;

    // Generator 1: loxodromic, moves points toward fixed point at (0.7, 0.0)
    // Multiplier k = e^(r + iθ) for attraction/rotation
    float r1 = 0.7, theta1 = 0.4 + 0.1*sin(phase);
    vec2 k1 = vec2(exp(r1)*cos(theta1), exp(r1)*sin(theta1));

    // Generator 2: loxodromic, fixed at (-0.5, 0.5)
    float r2 = 0.6, theta2 = -0.5 + 0.08*cos(phase * 1.3);
    vec2 k2 = vec2(exp(r2)*cos(theta2), exp(r2)*sin(theta2));

    // Fixed points for the two generators (on/near unit circle)
    vec2 fp1a = vec2(0.70, 0.0), fp1b = vec2(-0.70, 0.0);   // g1 attracting/repelling
    vec2 fp2a = vec2(-0.5, 0.6) / length(vec2(-0.5, 0.6));  // normalize to unit
    vec2 fp2b = vec2( 0.5,-0.6) / length(vec2( 0.5,-0.6));

    // Build Möbius transformations from fixed points and multiplier
    // g(z) = (k*fp1a*(z-fp1b) - fp1b*(z-fp1a)) / ((k*(z-fp1b) - (z-fp1a))
    // Simplified: Möbius with given fixed points
    // For g1:
    vec2 a1 = cmul(k1, fp1a) - fp1b;
    vec2 b1 = cmul(fp1a, fp1b) * vec2(-1.0,0.0) + cmul(k1, cmul(fp1a, fp1b));
    // This gets complex; use a simplified parameterization instead.

    // Direct Schottky approach: pair of circles
    // C1: center c1, radius r1; C2: center c2, radius r2
    vec2 c1 = vec2(0.0, 0.55);  float rad1 = 0.25 + 0.05*sin(phase);
    vec2 c2 = vec2(0.0,-0.55);  float rad2 = 0.25 + 0.05*sin(phase+1.57);

    // Count how deep z falls into the limit set fractal
    // by checking membership in the Cantor set construction
    float depth_val = 0.0;
    vec2 w = z;
    float scale = 1.0;

    for (int i = 0; i < LIMIT_ITER; i++) {
        float d1 = length(w - c1);
        float d2 = length(w - c2);

        if (d1 < rad1) {
            // Invert through C1: w → c1 + rad1²/(w-c1)
            vec2 dv = w - c1;
            w = c1 + rad1*rad1/dot(dv,dv) * dv;
            depth_val += scale;
            scale *= 0.5;
        } else if (d2 < rad2) {
            vec2 dv = w - c2;
            w = c2 + rad2*rad2/dot(dv,dv) * dv;
            depth_val += scale;
            scale *= 0.5;
        } else {
            break;
        }

        if (length(w) > 1.5) break;
    }

    return depth_val;
}

float hypDist(vec2 z) {
    float r = clamp(length(z), 0.0, 0.9999999);
    return log((1.0+r)/(1.0-r));
}

void main() {
    vec2 uv = (gl_FragCoord.xy - 0.5*u_resolution.xy) / min(u_resolution.x, u_resolution.y);
    float r = length(uv);
    if (r >= 1.0) { gl_FragColor = vec4(0.0,0.0,0.0,1.0); return; }

    float hd    = hypDist(uv);
    float depth = clamp(1.0 - hd/5.5, 0.0, 1.0);

    // ── background: dim {7,3} tiling ──────────────────────────────────────
    int parity73;
    vec2 fd73  = fold73(uv, parity73);
    FundTri tri73 = makeFundTri73();
    float d_arc73 = abs(length(fd73 - vec2(tri73.acx,tri73.acy)) - sqrt(tri73.aR2));
    float edge73  = 1.0 - smoothstep(0.0, 0.008, d_arc73);

    vec3 base = (parity73==0) ? vec3(0.04,0.03,0.12) : vec3(0.06,0.04,0.16);
    base = mix(base, vec3(0.2,0.18,0.35)*depth, edge73*0.5);

    // ── Kleinian limit set ─────────────────────────────────────────────────
    float ls = limitSetValue(uv, u_time);

    // Limit set glow: bright fractal dust
    if (ls > 0.01) {
        float t    = clamp(ls / 2.0, 0.0, 1.0);
        float glow_t = 1.0 - exp(-ls * 3.0);

        // Color the limit set: blue-white core, amber halo
        vec3 ls_core = vec3(0.5, 0.8, 1.0);
        vec3 ls_halo = vec3(1.0, 0.6, 0.2);
        vec3 ls_col  = mix(ls_halo, ls_core, t);

        base = mix(base, ls_col, glow_t * depth);
        base += ls_col * glow_t * 0.4 * depth;
    }

    // ── boundary glow: the limit set accumulates near unit circle ──────────
    float near_boundary = smoothstep(0.8, 1.0, r);
    float boundary_flicker = 0.5 + 0.5*sin(atan(uv.y,uv.x)*12.0 + u_time*1.5);
    base += vec3(0.1, 0.3, 0.8) * near_boundary * boundary_flicker * 0.6;

    // Schottky circles on boundary (where limit set lives)
    vec2 c1 = vec2(0.0, 0.55), c2 = vec2(0.0, -0.55);
    float d_c1 = abs(length(uv - c1) - 0.25);
    float d_c2 = abs(length(uv - c2) - 0.25);
    float circ = min(d_c1, d_c2);
    float circle_line = 1.0 - smoothstep(0.0, 0.006, circ);
    base = mix(base, vec3(0.3, 0.7, 1.0), circle_line * 0.4);

    // Outer glow
    float glow = exp(-(1.0-r)*14.0)*0.6;
    base += vec3(0.05, 0.15, 0.5)*glow;
    base *= 1.0 - 0.08*r*r;

    gl_FragColor = vec4(clamp(base,0.0,1.0),1.0);
}
